### ISSUE TITLE
Implement parsing of results returned by DoCmd[$]

### ISSUE THREAD

**Issue by smolvik1** [equinor/OpenServer#10]
**Merouane Hamdani 03.06.20:**
Not sure if anyone has experienced that but the output of the DoGet is bit funny in my view ... it outputs a string that needs to be splitted and parced ... attached is a simple example where I do make some IPR's sensitivites   (nb... I am choosing to querry the DoGet with the "$" as it s a way too fast compared to a normal loop)

**Comment by knudsvik** [comment]
See more details and code-example on this [Yammer thread](https://web.yammer.com/main/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiNzAwOTU1MjQ0MzM5MjAwIn0).
