### ISSUE TITLE
Additional wildcards handling

### ISSUE THREAD

**Issue by smolvik1** [equinor/OpenServer#16]
Facilitate for returning arrays when wildcards are submitted (chp. 3.6 of OpenServer manual): 
- Underscore (_)
- @ Sign and *
- @ Sign and ?
- @ Sign and #
- @ Sign and !

**Comment by knudsvik** [comment]
Does this include arrays like `'PROSPER.SIN.EQP.Devn.Data[1:3].Md'`? This is not being returned as an array today, but as a string with `|` dividers.

**Comment by smolvik1** [comment]
Will include ':' handling in DoGet

**Comment by knudsvik** [comment]
When parts of arrays ( `[1:3]`) are handled in DoGet method, two test functions should be uncommented, and line 52 changed in test_openserver.py
