### ISSUE TITLE
DoSet failling when no arguments needed 

### ISSUE THREAD

**Issue by miroine** [equinor/OpenServer#23]
Some DoSet commands are failling when no arguments is provided 
![image](https://user-images.githubusercontent.com/40567543/85021017-817b8c80-b171-11ea-9663-bbd8ea749bcd.png)

passing a command like this fails:
`c.DoSet('PROSPER.ANL.SYS.Sens.SensDB.Clear')  `

Workaround was to past an empty string as a value, however that should be defaulted and DoSet should never fail because of that

**Comment by smolvik1** [comment]
Changing the argument default input for Val should solve this: DoSet(self, Sv, Val='')

**Comment by knudsvik** [comment]
Merged in PR #24
