### ISSUE TITLE
WIN32.COM issues

### ISSUE THREAD

**Issue by tmmachinelearningclass** [equinor/OpenServer#27]
Hi,

Thank you very much for the library that you created. 

Today I found the following error message when I tried to connect to OpenServer. Is there any changes on the dependencies that creating this error? Sorry, I am not really familiar with this issue.
---------------------------------------------------------------------------
com_error                                 Traceback (most recent call last)
~\Anaconda3\lib\site-packages\win32com\client\dynamic.py in _GetGoodDispatch(IDispatch, clsctx)
     88                 try:
---> 89                         IDispatch = pythoncom.connect(IDispatch)
     90                 except pythoncom.ole_error:

com_error: (-2147221021, 'Operation unavailable', None, None)

During handling of the above exception, another exception occurred:

com_error                                 Traceback (most recent call last)
<ipython-input-7-0b387d1718d0> in <module>
      3 myConnection = osconnection()
      4 myConnection.setVerbose(verbose_output)
----> 5 myConnection.Connect()

~\openserver\osconnection.py in Connect(self)
     27                 if connected == 0 :
     28                         global server
---> 29                         server = win32com.client.Dispatch("PX32.OpenServer.1")
     30                         if verbose == True : print ("Establising connection")
     31                         connected = 1

~\Anaconda3\lib\site-packages\win32com\client\__init__.py in Dispatch(dispatch, userName, resultCLSID, typeinfo, UnicodeToString, clsctx)
     93   """
     94   assert UnicodeToString is None, "this is deprecated and will go away"
---> 95   dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
     96   return __WrapDispatch(dispatch, userName, resultCLSID, typeinfo, clsctx=clsctx)
     97 

~\Anaconda3\lib\site-packages\win32com\client\dynamic.py in _GetGoodDispatchAndUserName(IDispatch, userName, clsctx)
    112         else:
    113                 userName = str(userName)
--> 114         return (_GetGoodDispatch(IDispatch, clsctx), userName)
    115 
    116 def _GetDescInvokeType(entry, invoke_type):

~\Anaconda3\lib\site-packages\win32com\client\dynamic.py in _GetGoodDispatch(IDispatch, clsctx)
     89                         IDispatch = pythoncom.connect(IDispatch)
     90                 except pythoncom.ole_error:
---> 91                         IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
     92         else:
     93                 # may already be a wrapped class.

com_error: (-2147221164, 'Class not registered', None, None)

Regards,

Feldy

**Comment by smolvik1** [comment]
Appears to be related to issues establishing a connection and obtaining a petex license. Could you give it a go outside of anaconda?

**Comment by tmmachinelearningclass** [comment]
It's solved after I resintall my IPM software. Thanks!
