### ISSUE TITLE
PCP changes on artificial lift input data

### ISSUE THREAD

**Issue by ivanmolina7x** [equinor/OpenServer#32]
Hi!

I'm trying to modify an template file of a PCP well in prosper, and i need to change this variables that are in a pick list.
![1](https://github.com/equinor/OpenServer/assets/68932654/cb2185af-4e32-4a62-bbed-9e5324514a04)
I'm trying to use DoSet with its access string (os.SetValue('PROSPER.SIN.PCP.DesPump','1')), and everything apparently is fine, i use DoGet to obtain the variable (GetValue('PROSPER.SIN.PCP.DesPump')) and the change is done, but then, when i save the .out (DoCommand('PROSPER.SAVEFILE("path")')) and i open that file, the change is not done and it uses the options by default (template).
![image](https://github.com/equinor/OpenServer/assets/68932654/b2d4d09b-1f32-416b-a7b9-b5d08f28a324)
Then i went to the prosper functions and i found this functions that work for ESP to change information about AL input data (specifically pick list), do you know if there are functions like that to PCP?, or if there is currently a way to do it?
![image](https://github.com/equinor/OpenServer/assets/68932654/185f8af2-3d53-48c8-b70b-242d982b7caf)

**Comment by smolvik1** [comment]
This appears to be an issue with the Openserver functionality of Petroleum Experts, rather than functionality specific to this repository. My advice would be to contact Petroleum Experts for advise and/or submit a bug-report with them. 

Closing the issue
