### ISSUE TITLE
Bug from calling DoCmd('GAP.PREDINIT()')

### ISSUE THREAD

**Issue by Senechau-Nathan** [equinor/OpenServer#35]
Hello,

I'm new on GitHub but I'me a user of Petex and I find your module very practical for the automation of GAP simulation. 

Just for precise my message: I work on a windows machine with a virtuel environment Python version 3.12.3

What I m currently trying to do is to perform a run predict with a python script that use openserver module.

My problem is that I always have the same error when I use this sequence of command with the following date
start_date = ‘01/10/2010’; end_date = ‘01/12/2010’; time_step = 1 month:

```
import openserver as ops # module serveur pour communiquer avec PETEX.

path_subsurface = 'C:/Local/Outils_these/GIRASSOL/test_run_predict/Oil Field GL.gap' # (Note: here its my local path but you have to change it to test the script, I test with the sample file Oil Field GL.gar which I cannot attached in my report of bug because of the maximum size available here.)
C = ops.OpenServer() # chargement de l'object serveur PETEX.
C.connect() # connexion au serveur PETEX.
C.DoCmd('GAP.START()') # démarrage du logiciel GAP.
C.DoCmd(f"GAP.OPENFILE('{path_subsurface}')") # ouverture du file simulation.
    
C.DoSet("GAP.MOD[{PROD}].PREDINFO.START={01/10/2010}}") # établie la date de démarrage de la simulation.
C.DoSet("GAP.MOD[{PROD}].PREDINFO.END={01/12/2010}") # établie la date de fin de la simulation.
C.DoSet("GAP.MOD[{PROD}].PREDINFO.STEP=1") # établie le pas de temps de la simulation.
nb_run = C.DoCmd('GAP.PREDINIT()') # initialise le run predict.
for i in range(nb_run):
    C.DoCmd('GAP.PREDDOSTEP(0)') # réalise le run prédictif.
C.DoCmd('GAP.PREDEND()') # stop le processus.
```

Here I use DoCmd(‘GAP.PREDINIT()’) to initialize a run predict on a sample file 
And get the number of iterations corresponding to the schedule setting (start and end date and the time_step) but still I have this error into the DoCmd() function
```

OpenServer is connected
Invalid  period
OpenServer has been disconnected
Traceback (most recent call last):

  File ~\Documents\Virtualenv\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\local\outils_these\code_exergie\code\modules\module_sequentiel\these\module_couple\test_run_gap.py:47
    Run_GAP('01/10/2010', '01/12/2010', 1)

  File c:\local\outils_these\code_exergie\code\modules\module_sequentiel\these\module_couple\test_run_gap.py:30 in Run_GAP
    nb_run = C.DoCmd('GAP.PREDINIT()') # initialise le run predict.

  File ~\Documents\Virtualenv\Lib\site-packages\openserver\openserver.py:64 in DoCmd
    raise ValueError(self.error)

ValueError: Invalid  period
```

If you have any ideas on what can be possibly explain this error, what I don't understand is if the error is link to GAP, my script or the module OpenServer.

Thank you for attention to my message.

**Comment by smolvik1** [comment]
From the Openserver manual, the input for prediction start and end are number of days since 01/01/1900 00:00:00. 

This works fine on python 3.12.6:
`from openserver import OpenServer
from datetime import datetime

c = OpenServer()
c.connect()

FILE_PATH = r'C:\Oil Field.gap'

def days_since_1900(input_date):
    start_date = datetime(1900, 1, 1)
    # Ensure input_date is a datetime object
    if not isinstance(input_date, datetime):
        raise TypeError("input_date must be a datetime object")
    # Calculate the difference in days
    delta = input_date - start_date
    return delta.days


prediction_start = days_since_1900(datetime(2010,1,1))
prediction_end = days_since_1900(datetime(2010,12,1))

c.DoCmd('GAP.START()')
c.DoCmd(f'GAP.OPENFILE("{FILE_PATH}")')
c.DoSet('GAP.MOD[{PROD}].PREDINFO.START', prediction_start)
c.DoSet('GAP.MOD[{PROD}].PREDINFO.START', prediction_end)

c.disconnect()`

**Comment by Senechau-Nathan** [comment]
Hello, it work fine for me now thank you for your answer.
